### ISSUE TITLE
Не работает на не-русской локали

### ISSUE THREAD

**Issue by nbelyh** [Obsidian-pb/OSM2Visio#2]
Если установить локаль системы на English, то расширение не работает (координаты вычисляются некорректно). Скорее всего связано с разделителем целой и дробной части числа (точка или запятая)

**Comment by nbelyh** [comment]
Шаги чтобы воспроизвести:
Выбрать английскую (например) локаль в региональных настройках. И попробовать импортировать что угодно. В результате получается огромный масштаб и пустая диаграмма о_О

**Comment by Obsidian-pb** [comment]
Надо смотреть

**Comment by nbelyh** [comment]
Вот эта функция кажется проблемой (не уверен на 100% но скорее всего)
https://github.com/Obsidian-pb/OSM2Visio/blob/141897051ec647ee4a2bca068193710ea155ea7d/OSM2Visio/Code/DrawTools.cs#L75

**Comment by nbelyh** [comment]
Кажется починил
