### ISSUE TITLE
Стенсил не включен в установщик

### ISSUE THREAD

**Issue by nbelyh** [Obsidian-pb/OSM2Visio#3]
В коде используются стенсилы "План на местности" и "Водоснабжение"

**Comment by nbelyh** [comment]
@Obsidian-pb 
Там пароль на этих стенсилах. Там есть много кода? Может сделать отдельный стенсил, или допустим просто прямоугольники использовать для "здания" и линию для "дороги"?

**Comment by Obsidian-pb** [comment]
Я хочу это все программно реализовать. Использование стенсила как обязательного условия функционирования программы, как показал опыт, идея неудачная. Многие просто тупят, что его нужно вообще подключать. А некоторые и вове не понимают как это сделать.

**Comment by nbelyh** [comment]
Если рисовать всё руками, потеряется возможность настройки... Например вдруг кто-то захочет чтобы здания были другого цвета? А со стенсилом можно просто мастер поправить.

**Comment by Obsidian-pb** [comment]
Мн... надо подумать... Но тут смотри какой момент сразу. Нужно будет и трафарет локализовать тогда.

**Comment by nbelyh** [comment]
Сейчас добавил хоть какой-то стенсил чтобы работало из коробки

**Comment by nbelyh** [comment]
Насчет подключения и тупящих. Если стенсил установлен (зарегистрирован в системе), то никакой настройки от пользователя не требуется. Не нужно его прописывать в путях в advanced, визио не будет тормозить их сканируя, имя файла может быть любым. Программа может открывать стенсил по зарегистрированному имени. Все встроенные стенсилы так работают например.

**Comment by nbelyh** [comment]
Регмстрация собственно
https://github.com/Obsidian-pb/OSM2Visio/pull/6/commits/309d33d851ae4cd4499ccd56747d70b76e657c16#diff-b6a84af99128f2e1d183ac96e58e8ed2R133

**Comment by nbelyh** [comment]
Там в vba коде вроде функционала касательно  osm почти нет,  одна функция. Imho, перенести  в расширение и убрать макросы нафик :smiley:
